### ISSUE TITLE
False Negative? - CheckInconsistentMetadata does not find different tags if they are repeated

### ISSUE THREAD

**Issue by MzudemO** [Naxesss/MapsetChecks#11]
As you only check for Set difference, the following Mapset passes despite the tags being different between the difficulties:

Insane tags: `featured artist`

Extra Tags: `featured artist featured artist`

Should probably be a warning as I'm not sure if this is in fact unrankable?

**Comment by Naxesss** [comment]
For rankability I think it is enough that all diffs contain the same set of tags, hence this:

![image](https://user-images.githubusercontent.com/30292137/173253782-1b34719f-e38f-4d58-8114-3d45938a0e44.png)

The only case this falls apart is if you use quotes in the search (e.g. "featured artist" won't match "artist featured"). However, the RC seems to prefer not using quotes in searches and instead connecting multiple words with underscores where necessary (see GDer names).

If maps get dqed for this I'll probably change it, but from my perspective it is a non-issue.
