### ISSUE TITLE
Update ogg bitrate limit

### ISSUE THREAD

**Issue by tailsdk** [Naxesss/MapsetChecks#13]
Recently the ogg bitrate limit got changed to 208 instead of 192 so that Q6 wouldn't break guidelines, but it makes a problem stamp whenever it it is over 192 currently

**Comment by Naxesss** [comment]
Fixed in https://github.com/Naxesss/MapsetChecks/commit/29624d7cc85d52b53c66860949a82e75b11420bb (I think), but not yet released.
