### ISSUE TITLE
Concurrent Objects check efficiency

### ISSUE THREAD

**Issue by Alchyr** [Naxesss/MapsetChecks#5]
Currently, it iterates through all objects except those that have already been checked. It could be made more efficient by moving to the next object as soon as it reaches an object more than 10 ms past the current one (assuming objects are sorted).

**Comment by Naxesss** [comment]
Good catch, also ended up using the actual arrays instead of first placing them into lists and then performing except for each iteration; makes things a bit more space efficient as well.
