### ISSUE TITLE
CheckAdditionalMarkers returns false positives

### ISSUE THREAD

**Issue by rorre** [Naxesss/MapsetChecks#6]
Easy example: "Believer" (https://osu.ppy.sh/beatmapsets/1079693#osu/2258888)
[image](https://i.imgur.com/gzIlVDf.png)

seems to be caused by this regex: `(?i)([^A-Za-z0-9]+)?(ver(\\.|sion)?|size)([^A-Za-z0-9]+)?$` (can't seem to find CheckAdditionalMarkers in this repo tho)
the regex above matches Belie`ver` which i believe isnt expected as there is no marker inside the title.

**Comment by Naxesss** [comment]
yeah I removed this check entirely in exchange for covering the last "version/size"-type metadata standardization, "(Sped Up Ver.)", see commit message below

![](https://i.imgur.com/mtdKibP.png)

~~have a few more things I want to fix before I release the current version~~ done and released
